# Site settings
title:       Met Office Lab
email:       met-office-lab@gmail.com
author:      Met Office Lab
description: "A lab at the Met Office for creating things!"
baseurl:     ""
url:         http://www.informaticslab.co.uk
github-url:  http://github.com/met-office-lab/
twitter-url: http://twitter.com/metolab/


# Google analytics
google_analytics: 'UA-60337429-1'

# Optional features
animated:           false
show_related_posts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  sass_dir: _bootstrap-sass/assets/stylesheets

collections:
    profiles:
        output: true
        permalink: /people/:path/
    projects:
        output: true
        permalink: /projects/:path/
    concept-notes:
        output: true
        permalink: /concept-notes/:path/
    carousel-items:
        output: true
        permalink: /carousel-items/:path/
